#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#import sys
#print(sys.version)

#from selenium import webdriver
#from selenium.webdriver.common.keys import Keys
#from selenium.webdriver.common.by import By

#driver = webdriver.Chrome('chromedriver')
#driver.get("https://hkairportluckydraw.com/")
#driver.implicitly_wait(2)

#driver.find_element_by_xpath("//img[@src='https://hkairportluckydrawimg.s3.ap-east-1.amazonaws.com/img/flighticon.png']").click()
#firstbutton = driver.find_element_by_css_selector("#app > div > div.wrapper > div.content > div > div > div.action-wrapper > div > div.content--bottom > div > div > a > img")
#driver.execute_script('$("#app > div > div.wrapper > div.content > div > div > div.desktop-element > div.action-wrapper-desktop > div.wrapper__right > div > div > a > img").click()')

#driver.implicitly_wait(10)
#driver.find_element_by_xpath('//button[text()="立即抽獎"]').click()

#driver.implicitly_wait(10)
#driver.find_element_by_xpath('//button[text()="提交"]').click()

#driver.close()

from selenium import webdriver
import time

driver = webdriver.Chrome('chromedriver')

driver.get("https://hkairportluckydraw.com/")
time.sleep(3)

driver.execute_script('document.querySelector("#app > div > div.wrapper > div.content > div > div > div.desktop-element > div.action-wrapper-desktop > div.wrapper__right > div > div > a").click()')
time.sleep(3)

driver.execute_script('document.querySelector("#app > div > div.wrapper > div.btn.btn-container > a").click()')
time.sleep(3)

driver.execute_script('document.querySelector("#app > div > div.popup.active > div > div.popup__content > div.form-contact > div.form-group.form-group-2 > input[type=tel]").focus()')
Inputelement = driver.find_element_by_css_selector("#app > div > div.popup.active > div > div.popup__content > div.form-contact > div.form-group.form-group-2 > input[type=tel]")
Inputelement.send_keys('67789751')
time.sleep(3)

driver.execute_script('document.querySelector("#app > div > div.popup.active > div > div.btn.btn-container > a").click()')

#driver.close()
